backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
# This line should *not* be indented
publish_mode: editorial_workflow
# This line should *not* be indented
media_folder: "netlifycms/img" # Media files will be stored in the repo under images/uploads
# These lines should *not* be indented
public_folder: "netlifycms/img" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "netlifycms/collection/Articles" # Used in routes, e.g., /admin/collections/Articles
    label: "Articles" # Used in the UI
    folder: "netlify/content" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "Articles"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}